version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run:
          name: "Check enviroment"
          command: sudo sh scripts/cibuild.sh
      - run:
          name: "Prepare"
          command: mkdir build && cd build
      - run:
          name: "Build"
          command: cmake .. && make -j4

